# Generated by Django 2.0 on 2019-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190410_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='executives',
            field=models.ManyToManyField(blank=True, null=True, to='portal.Executive'),
        ),
    ]
